# Theme settings
doks:
    baseurl:
    color_theme: # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: Hass.Codes
            image:
        nav:
            - item_name: Home
              item_url: '/'
            - item_name: Contact
              item_url: '/#'
            - item_name: Newsletter
              item_url: 'http://newsletter.hass.codes/'
    footer:
        content:
            logo:
                text: Hass.Codes
                image:
            copyright: Copyright &copy; 2018. - Hass.Codes<br>All rights reserved.
        social_list:
            - network_name: twitter
              profile_url: 'https://twitter.com/sas1ni69'
            - network_name: github
              profile_url: 'https://github.com/sas1ni69'
            - network_name: stackoverflow
              profile_url: 'https://stackoverflow.com/users/702436/hassanin-ahmed'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
